// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	image "image"
	color "image/color"

	mock "github.com/stretchr/testify/mock"
)

// Image is an autogenerated mock type for the Image type
type Image struct {
	mock.Mock
}

// At provides a mock function with given fields: x, y
func (_m *Image) At(x int, y int) color.Color {
	ret := _m.Called(x, y)

	var r0 color.Color
	if rf, ok := ret.Get(0).(func(int, int) color.Color); ok {
		r0 = rf(x, y)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(color.Color)
		}
	}

	return r0
}

// Bounds provides a mock function with given fields:
func (_m *Image) Bounds() image.Rectangle {
	ret := _m.Called()

	var r0 image.Rectangle
	if rf, ok := ret.Get(0).(func() image.Rectangle); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(image.Rectangle)
	}

	return r0
}

// ColorModel provides a mock function with given fields:
func (_m *Image) ColorModel() color.Model {
	ret := _m.Called()

	var r0 color.Model
	if rf, ok := ret.Get(0).(func() color.Model); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(color.Model)
		}
	}

	return r0
}
